image:
  repository: IMAGE_URI
  tag: "latest"
  pullPolicy: Always

replicaCount: 3

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
  metricsPort: 9090
  metricsTargetPort: 9090

ingress:
  enabled: false
  host: app.example.com

cloudProvider: Kubernetes