name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r app/requirements.txt

      - name: Build Docker image
        run: |
          cd app
          docker build -t multi-cloud-app:${{ github.ref_name }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag multi-cloud-app:${{ github.ref_name }} ${{ secrets.DOCKER_USERNAME }}/multi-cloud-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-cloud-app:${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            - Auto‑generated release notes
          draft: false
          prerelease: false